### ISSUE TITLE
BLAS detection fails on Ubuntu 18.04

### ISSUE THREAD

**Issue by Lord-Kamina** [aubio/aubio#279]
I noticed this while trying to understand why my CI was failing to build a project that depends on audio.

I'm building aubio like so:

```'/home/semaphore/performous/3rdparty/aubio/waf' --verbose configure build install --enable-blas --disable-atlas --disable-accelerate --enable-fftw3f --disable-sndfile --disable-avcodec --disable-double --disable-samplerate --disable-docs --disable-wavread --disable-wavwrite --disable-tests --notests --disable-examples --disable-apple-audio --disable-fat --disable-jack --prefix='/home/semaphore/performous/build.gcc/aubio-prefix' --out=/home/semaphore/performous/build.gcc/aubio-prefix --top='/home/semaphore/performous/3rdparty/aubio/'```

For the record, mind that the exact same commands work perfectly on Ubuntu 16.04.

This gives me the following error:

```In file included from ../../3rdparty/aubio/src/spectral/dct.c:33:0:
../../3rdparty/aubio/src/aubio_priv.h:87:2: error: #error "HAVE_BLAS was defined, but no blas header was found"
 #error "HAVE_BLAS was defined, but no blas header was found"```

If I try to find cblas.h, this is what I get:
```
semaphore@semaphore-vm:~/performous/3rdparty$ sudo find / -iname cblas.h
/usr/include/x86_64-linux-gnu/cblas.h
```
Checking update-alternatives...

``` 
semaphore@semaphore-vm:~/performous/3rdparty$ sudo update-alternatives --config libblas.so
update-alternatives: error: no alternatives for libblas.so

semaphore@semaphore-vm:~/performous/3rdparty$ sudo update-alternatives --config libblas.so.3
update-alternatives: error: no alternatives for libblas.so.3

sudo update-alternatives --config libblas.so-x86_64-linux-gnu
There is only one alternative in link group libblas.so-x86_64-linux-gnu (providing /usr/lib/x86_64-linux-gnu/libblas.so): /usr/lib/x86_64-linux-gnu/openblas/libblas.so
```
Finally, if I do the following:

```
semaphore@semaphore-vm:~/performous/3rdparty$ sudo mkdir /usr/include/x86_64-linux-gnu/openblas/
semaphore@semaphore-vm:~/performous/3rdparty$ sudo ln -sf /usr/include/x86_64-linux-gnu/cblas.h /usr/include/x86_64-linux-gnu/openblas/cblas.h
```
it works.

I am not certain this is actually an issue on aubio's side but my solution is very definitely far from ideal.

**Comment by Lord-Kamina** [comment]
Some further information:
`/usr/include/x86_64-linux-gnu/cblas.h` is a symlink to `/usr/include/x86_64-linux-gnu/cblas-openblas.h` and there does not appear to be an openblas/cblas.h.

If I manually specify `CFLAGS=-DHAVE_CBLAS_H` it works perfectly.

So, this DOES seem to be an issue in aubio's wscript. I don't know if maybe it used to be `openblas/cblas.h`and it changed, or if Bionic is somehow special or what, but aubio is looking for the blas header in the wrong location.

**Comment by Lord-Kamina** [comment]
Turns out this can be fixed by setting BLA_VENDOR to OpenBLAS before trying to find it in my CMake script.

**Comment by achernet** [comment]
bumping this zombie issue

I ran into a similar issue on a different distro and made a PR: https://github.com/aubio/aubio/pull/442
