### ISSUE TITLE
aubio is unable to find numpy C includes (MacOS, virtualenv)

### ISSUE THREAD

**Issue by rec** [aubio/aubio#320]
Hello again!

This is an old problem with a known workaround, but I want to figure out a way to fix this "at the source" - and yes, that means I intend to fix it myself eventually.  :-)

----

On a clean virtualenv on MacOS 10.14.6, `aubio` fails to install from  `pip` or any other compilation-based install method because it is unable to find the numpy C includes, with an error I'm sure you're familiar with:

```
  In file included from python/ext/aubiomodule.c:2:
  python/ext/aubio-types.h:17:10: fatal error: 'numpy/arrayobject.h' file not found
  #include <numpy/arrayobject.h>
           ^~~~~~~~~~~~~~~~~~~~~
```

Of course, a quick tweak of `CFLAGS` and it all works - in my case it was

```
export CFLAGS=-I/Users/tom/.virtualenvs/vl8/lib/python3.9/site-packages/numpy/core/include
```

(And it isn't a 3.9 thing, I reproduced it with an earlier version.  Aubio works perfectly on Python 3.8, btw.)

However, I'm planning to be writing a (free, open-source) application that I will be distributing through pip, and I'm worried that other MacOS users will run into the same installation hitch, so I wanted to file this issue.

I don't know anything about "from source" built packages or I'd do it right now.  

My guess is that it's some magic in setup.py, complexified by the fact it would first have to make sure that `numpy` was installed, and then call `np.get_include()`, and then add it into the environment...

So this might be some work.  I will get to it, or perhaps you have a quickie solution.

----

Or perhaps it's some misconfiguration here.  I don't think so, though - the command line in the build just doesn't seem to know about the current virtualenv.  My Python environment is more pristine than my libraries! :-D

----

Overall, I have been tremendously productive with aubio and look forward to a great deal of work with it in the future.

**Comment by shakfu** [comment]
I just the same issue why installing audio on python 3.9.5

**Comment by niliha** [comment]
I found out that installing numpy in advance (`pip install numpy`) also resolves the issue.
For a proper fix, aubio's  `setup.py` would need to get fixed as described [here](https://stackoverflow.com/questions/27817190/what-does-cmdclass-do-in-pythons-setuptools).

But I'm not sure if it's worth issuing a pull request, since there seems to be little or no reaction to open pull requests
